USE rgdatabase;
GO

CREATE TABLE ZAEHLER (ID INT, BEZEICHNUNG nvarchar(30), ANZAHL INT);
GO
INSERT INTO ZAEHLER(ID, BEZEICHNUNG, ANZAHL) VALUES (1, 'HANS',0)
GO
INSERT INTO ZAEHLER(ID, BEZEICHNUNG, ANZAHL) VALUES (2, 'KARL',0)
GO
